// THIS   AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _tpa_obu_lcm_obstacle_v_h
#define _tpa_obu_lcm_obstacle_v_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _tpa_obu_lcm_obstacle_v tpa_obu_lcm_obstacle_v;
struct _tpa_obu_lcm_obstacle_v
{
    int64_t    timestamp;
    int32_t    nums;
    float      *distance;
    float      *worldx;
};

/**
 * Create a deep copy of a tpa_obu_lcm_obstacle_v.
 * When no longer needed, destroy it with tpa_obu_lcm_obstacle_v_destroy()
 */
tpa_obu_lcm_obstacle_v* tpa_obu_lcm_obstacle_v_copy(const tpa_obu_lcm_obstacle_v* to_copy);

/**
 * Destroy an instance of tpa_obu_lcm_obstacle_v created by tpa_obu_lcm_obstacle_v_copy()
 */
void tpa_obu_lcm_obstacle_v_destroy(tpa_obu_lcm_obstacle_v* to_destroy);

/**
 * Identifies a single subscription.  This   an opaque data type.
 */
typedef struct _tpa_obu_lcm_obstacle_v_subscription_t tpa_obu_lcm_obstacle_v_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * tpa_obu_lcm_obstacle_v   received.
 */
typedef void(*tpa_obu_lcm_obstacle_v_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const tpa_obu_lcm_obstacle_v *msg, void *userdata);

/**
 * Publish a message of type tpa_obu_lcm_obstacle_v using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int tpa_obu_lcm_obstacle_v_publish(lcm_t *lcm, const char *channel, const tpa_obu_lcm_obstacle_v *msg);

/**
 * Subscribe to messages of type tpa_obu_lcm_obstacle_v using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message   received.
 *                This function   invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it   invoked.
 * @return 0 on success, <0 if an error occured
 */
tpa_obu_lcm_obstacle_v_subscription_t* tpa_obu_lcm_obstacle_v_subscribe(lcm_t *lcm, const char *channel, tpa_obu_lcm_obstacle_v_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by tpa_obu_lcm_obstacle_v_subscribe()
 */
int tpa_obu_lcm_obstacle_v_unsubscribe(lcm_t *lcm, tpa_obu_lcm_obstacle_v_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int tpa_obu_lcm_obstacle_v_subscription_set_queue_capacity(tpa_obu_lcm_obstacle_v_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type tpa_obu_lcm_obstacle_v into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to tpa_obu_lcm_obstacle_v_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int tpa_obu_lcm_obstacle_v_encode(void *buf, int offset, int maxlen, const tpa_obu_lcm_obstacle_v *p);

/**
 * Decode a message of type tpa_obu_lcm_obstacle_v from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with tpa_obu_lcm_obstacle_v_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message   stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int tpa_obu_lcm_obstacle_v_decode(const void *buf, int offset, int maxlen, tpa_obu_lcm_obstacle_v *msg);

/**
 * Release resources allocated by tpa_obu_lcm_obstacle_v_decode()
 * @return 0
 */
int tpa_obu_lcm_obstacle_v_decode_cleanup(tpa_obu_lcm_obstacle_v *p);

/**
 * Check how many bytes are required to encode a message of type tpa_obu_lcm_obstacle_v
 */
int tpa_obu_lcm_obstacle_v_encoded_size(const tpa_obu_lcm_obstacle_v *p);

// LCM support functions. Users should not call these
int64_t __tpa_obu_lcm_obstacle_v_get_hash(void);
uint64_t __tpa_obu_lcm_obstacle_v_hash_recursive(const __lcm_hash_ptr *p);
int     __tpa_obu_lcm_obstacle_v_encode_array(void *buf, int offset, int maxlen, const tpa_obu_lcm_obstacle_v *p, int elements);
int     __tpa_obu_lcm_obstacle_v_decode_array(const void *buf, int offset, int maxlen, tpa_obu_lcm_obstacle_v *p, int elements);
int     __tpa_obu_lcm_obstacle_v_decode_array_cleanup(tpa_obu_lcm_obstacle_v *p, int elements);
int     __tpa_obu_lcm_obstacle_v_encoded_array_size(const tpa_obu_lcm_obstacle_v *p, int elements);
int     __tpa_obu_lcm_obstacle_v_clone_array(const tpa_obu_lcm_obstacle_v *p, tpa_obu_lcm_obstacle_v *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
