// THIS   AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "tpa_obu_lcm_obstacle_v.h"

static int __tpa_obu_lcm_obstacle_v_hash_computed;
static uint64_t __tpa_obu_lcm_obstacle_v_hash;

uint64_t __tpa_obu_lcm_obstacle_v_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __tpa_obu_lcm_obstacle_v_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__tpa_obu_lcm_obstacle_v_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xbc5049b12d1b00f9LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __tpa_obu_lcm_obstacle_v_get_hash(void)
{
    if (!__tpa_obu_lcm_obstacle_v_hash_computed) {
        __tpa_obu_lcm_obstacle_v_hash = (int64_t)__tpa_obu_lcm_obstacle_v_hash_recursive(NULL);
        __tpa_obu_lcm_obstacle_v_hash_computed = 1;
    }

    return __tpa_obu_lcm_obstacle_v_hash;
}

int __tpa_obu_lcm_obstacle_v_encode_array(void *buf, int offset, int maxlen, const tpa_obu_lcm_obstacle_v *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nums), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].distance, p[element].nums);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].worldx, p[element].nums);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int tpa_obu_lcm_obstacle_v_encode(void *buf, int offset, int maxlen, const tpa_obu_lcm_obstacle_v *p)
{
    int pos = 0, thislen;
    int64_t hash = __tpa_obu_lcm_obstacle_v_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __tpa_obu_lcm_obstacle_v_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __tpa_obu_lcm_obstacle_v_encoded_array_size(const tpa_obu_lcm_obstacle_v *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int32_t_encoded_array_size(&(p[element].nums), 1);

        size += __float_encoded_array_size(p[element].distance, p[element].nums);

        size += __float_encoded_array_size(p[element].worldx, p[element].nums);

    }
    return size;
}

int tpa_obu_lcm_obstacle_v_encoded_size(const tpa_obu_lcm_obstacle_v *p)
{
    return 8 + __tpa_obu_lcm_obstacle_v_encoded_array_size(p, 1);
}

int __tpa_obu_lcm_obstacle_v_decode_array(const void *buf, int offset, int maxlen, tpa_obu_lcm_obstacle_v *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nums), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].distance = (float*) lcm_malloc(sizeof(float) * p[element].nums);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].distance, p[element].nums);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].worldx = (float*) lcm_malloc(sizeof(float) * p[element].nums);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].worldx, p[element].nums);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __tpa_obu_lcm_obstacle_v_decode_array_cleanup(tpa_obu_lcm_obstacle_v *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int32_t_decode_array_cleanup(&(p[element].nums), 1);

        __float_decode_array_cleanup(p[element].distance, p[element].nums);
        if (p[element].distance) free(p[element].distance);

        __float_decode_array_cleanup(p[element].worldx, p[element].nums);
        if (p[element].worldx) free(p[element].worldx);

    }
    return 0;
}

int tpa_obu_lcm_obstacle_v_decode(const void *buf, int offset, int maxlen, tpa_obu_lcm_obstacle_v *p)
{
    int pos = 0, thislen;
    int64_t hash = __tpa_obu_lcm_obstacle_v_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __tpa_obu_lcm_obstacle_v_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int tpa_obu_lcm_obstacle_v_decode_cleanup(tpa_obu_lcm_obstacle_v *p)
{
    return __tpa_obu_lcm_obstacle_v_decode_array_cleanup(p, 1);
}

int __tpa_obu_lcm_obstacle_v_clone_array(const tpa_obu_lcm_obstacle_v *p, tpa_obu_lcm_obstacle_v *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int32_t_clone_array(&(p[element].nums), &(q[element].nums), 1);

        q[element].distance = (float*) lcm_malloc(sizeof(float) * q[element].nums);
        __float_clone_array(p[element].distance, q[element].distance, p[element].nums);

        q[element].worldx = (float*) lcm_malloc(sizeof(float) * q[element].nums);
        __float_clone_array(p[element].worldx, q[element].worldx, p[element].nums);

    }
    return 0;
}

tpa_obu_lcm_obstacle_v *tpa_obu_lcm_obstacle_v_copy(const tpa_obu_lcm_obstacle_v *p)
{
    tpa_obu_lcm_obstacle_v *q = (tpa_obu_lcm_obstacle_v*) malloc(sizeof(tpa_obu_lcm_obstacle_v));
    __tpa_obu_lcm_obstacle_v_clone_array(p, q, 1);
    return q;
}

void tpa_obu_lcm_obstacle_v_destroy(tpa_obu_lcm_obstacle_v *p)
{
    __tpa_obu_lcm_obstacle_v_decode_array_cleanup(p, 1);
    free(p);
}

int tpa_obu_lcm_obstacle_v_publish(lcm_t *lc, const char *channel, const tpa_obu_lcm_obstacle_v *p)
{
      int max_data_size = tpa_obu_lcm_obstacle_v_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = tpa_obu_lcm_obstacle_v_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _tpa_obu_lcm_obstacle_v_subscription_t {
    tpa_obu_lcm_obstacle_v_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void tpa_obu_lcm_obstacle_v_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    tpa_obu_lcm_obstacle_v p;
    memset(&p, 0, sizeof(tpa_obu_lcm_obstacle_v));
    status = tpa_obu_lcm_obstacle_v_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding tpa_obu_lcm_obstacle_v!!!\n", status);
        return;
    }

    tpa_obu_lcm_obstacle_v_subscription_t *h = (tpa_obu_lcm_obstacle_v_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    tpa_obu_lcm_obstacle_v_decode_cleanup (&p);
}

tpa_obu_lcm_obstacle_v_subscription_t* tpa_obu_lcm_obstacle_v_subscribe (lcm_t *lcm,
                    const char *channel,
                    tpa_obu_lcm_obstacle_v_handler_t f, void *userdata)
{
    tpa_obu_lcm_obstacle_v_subscription_t *n = (tpa_obu_lcm_obstacle_v_subscription_t*)
                       malloc(sizeof(tpa_obu_lcm_obstacle_v_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 tpa_obu_lcm_obstacle_v_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg tpa_obu_lcm_obstacle_v LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int tpa_obu_lcm_obstacle_v_subscription_set_queue_capacity (tpa_obu_lcm_obstacle_v_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int tpa_obu_lcm_obstacle_v_unsubscribe(lcm_t *lcm, tpa_obu_lcm_obstacle_v_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe tpa_obu_lcm_obstacle_v_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

